### ISSUE TITLE
Android Gallery didn't open

### ISSUE THREAD

**Issue by PsyHoGK** [mozzius/community-handles#7]
It happens on Blue|Graysky clients, after trying to attach something, gallery didnt respond. 
Permission to files granted and application react if you trying forbid to access.
Other applications works perfect with gallery and files too.
Lineage OS 17.1
P.S. If interested, BlueSky client crashed after trying to fast tap to the attach file button after several times. I can't reproduce it on Gray client due additional menu.

**Comment by mozzius** [comment]
Please file an issue in the mozzius/graysky repo
